### ISSUE TITLE
Selection nearly impossible

### ISSUE THREAD

**Issue by HacktheTime** [Greeenman999/LibrarianTradeFinder#35] opened 2023-09-30 20:54 UTC
You set a maximum to the integers however this makes putting the right values in (if even possible) extremely hard at least if you accept multiple different trades.

You just cant  modify max values pretty much. for example if you set 24 as value you cant delete either number as you would be below minimum cost even if you want to go to 40 or something

**Comment by Greeenman999** [comment] 2023-10-16 16:54
Hi thanks for reporting, this is a duplicate of #22.

**Closed by Greeenman999** 2023-10-16 16:54 UTC
Labels: duplicate
